import type { ChannelCollectorType } from "@/server/channels/definition"
import type {
  ChannelColorPreset,
  ChannelDisplayStyle,
  ChannelMetaDisplayMode,
  ChannelMetaPosition,
  ChannelType,
} from "@/server/channels/display-config"

export type NewsnowCategorySeed = {
  categoryName: string
  slug: string
  icon: string
  color: string
  sort: number
}

export type NewsnowChannelCatalogEntry = {
  sourceId: string
  definitionKey: string
  siteSlug: string
  channelSlug: string
  siteName: string
  channelName: string
  homepageUrl: string
  description: string
  collectorType: ChannelCollectorType
  rssUrl?: string
  crawlIntervalSeconds: number
  snapshotIntervalSeconds: number
  categorySlugs: string[]
  colorPreset: ChannelColorPreset
  displayStyle: ChannelDisplayStyle
  channelType: ChannelType
  itemLimit: number
  metaDisplay: ChannelMetaDisplayMode
  metaPosition: ChannelMetaPosition
  showUpdatedAt: boolean
  subtitle?: string | null
  isCrawlEnabled: boolean
  isHomeVisible: boolean
  isSubscribable: boolean
  status: "draft" | "active" | "disabled"
  siteSort: number
  sort: number
}

type CatalogInput = Omit<
  NewsnowChannelCatalogEntry,
  | "description"
  | "displayStyle"
  | "channelType"
  | "metaDisplay"
  | "metaPosition"
  | "showUpdatedAt"
  | "snapshotIntervalSeconds"
  | "isSubscribable"
>

export const newsnowCategorySeeds: NewsnowCategorySeed[] = [
  {
    categoryName: "综合",
    slug: "general",
    icon: "newspaper",
    color: "#1E40AF",
    sort: 10,
  },
  {
    categoryName: "科技",
    slug: "tech",
    icon: "cpu",
    color: "#047857",
    sort: 20,
  },
  {
    categoryName: "财经",
    slug: "finance",
    icon: "chart-line",
    color: "#B45309",
    sort: 30,
  },
  {
    categoryName: "国际",
    slug: "world",
    icon: "globe-2",
    color: "#7C3AED",
    sort: 40,
  },
  {
    categoryName: "娱乐",
    slug: "entertainment",
    icon: "sparkles",
    color: "#DC2626",
    sort: 50,
  },
]

const catalogInputs: CatalogInput[] = [
  channel(
    "v2ex-share",
    "v2ex.share",
    "v2ex",
    "share",
    "V2EX",
    "V2EX 最新分享",
    "https://v2ex.com/",
    "adapter",
    600,
    ["tech"],
    "slate",
    10,
    10,
    "最新分享",
  ),
  channel(
    "zhihu",
    "zhihu.hot-list",
    "zhihu",
    "hot-list",
    "知乎",
    "知乎热榜",
    "https://www.zhihu.com",
    "adapter",
    600,
    ["general"],
    "blue",
    20,
    10,
    "热榜",
  ),
  channel(
    "weibo",
    "weibo.hot-search",
    "weibo",
    "hot-search",
    "微博",
    "微博热搜",
    "https://weibo.com",
    "adapter",
    120,
    ["general", "entertainment"],
    "red",
    30,
    10,
    "实时热搜",
  ),
  channel(
    "zaobao",
    "zaobao.realtime",
    "zaobao",
    "realtime",
    "联合早报",
    "联合早报实时",
    "https://www.zaobao.com",
    "adapter",
    1800,
    ["world"],
    "red",
    40,
    10,
    "实时",
  ),
  channel(
    "coolapk",
    "coolapk.hot-list",
    "coolapk",
    "hot-list",
    "酷安",
    "酷安今日最热",
    "https://coolapk.com",
    "adapter",
    600,
    ["tech"],
    "green",
    50,
    10,
    "今日最热",
  ),
  channel(
    "mktnews-flash",
    "mktnews.flash",
    "mktnews",
    "flash",
    "MKTNews",
    "MKTNews 快讯",
    "https://mktnews.net",
    "adapter",
    120,
    ["finance"],
    "indigo",
    60,
    10,
    "快讯",
    50,
  ),
  channel(
    "wallstreetcn-quick",
    "wallstreetcn.quick",
    "wallstreetcn",
    "quick",
    "华尔街见闻",
    "华尔街见闻快讯",
    "https://wallstreetcn.com/",
    "adapter",
    300,
    ["finance"],
    "blue",
    70,
    10,
    "快讯",
  ),
  channel(
    "wallstreetcn-news",
    "wallstreetcn.news",
    "wallstreetcn",
    "news",
    "华尔街见闻",
    "华尔街见闻最新",
    "https://wallstreetcn.com/",
    "adapter",
    1800,
    ["finance"],
    "blue",
    70,
    20,
    "最新",
  ),
  channel(
    "wallstreetcn-hot",
    "wallstreetcn.hot",
    "wallstreetcn",
    "hot",
    "华尔街见闻",
    "华尔街见闻最热",
    "https://wallstreetcn.com/",
    "adapter",
    1800,
    ["finance"],
    "blue",
    70,
    30,
    "最热",
  ),
  channel(
    "36kr-quick",
    "36kr.quick",
    "36kr",
    "quick",
    "36氪",
    "36氪快讯",
    "https://36kr.com",
    "adapter",
    600,
    ["tech"],
    "blue",
    80,
    10,
    "快讯",
  ),
  channel(
    "36kr-renqi",
    "36kr.renqi",
    "36kr",
    "renqi",
    "36氪",
    "36氪人气榜",
    "https://36kr.com",
    "adapter",
    600,
    ["tech"],
    "blue",
    80,
    20,
    "人气榜",
  ),
  channel(
    "douyin",
    "douyin.hot-list",
    "douyin",
    "hot-list",
    "抖音",
    "抖音热榜",
    "https://www.douyin.com",
    "adapter",
    600,
    ["general", "entertainment"],
    "gray",
    90,
    10,
    "热榜",
  ),
  channel(
    "hupu",
    "hupu.daily-hot",
    "hupu",
    "daily-hot",
    "虎扑",
    "虎扑主干道热帖",
    "https://hupu.com",
    "adapter",
    600,
    ["general"],
    "red",
    100,
    10,
    "主干道热帖",
  ),
  channel(
    "aihot",
    "aihot.all",
    "aihot",
    "all",
    "AIHOT",
    "AIHOT 全站动态",
    "https://aihot.virxact.com/all",
    "adapter",
    300,
    ["tech"],
    "blue",
    110,
    10,
    "动态",
  ),
  channel(
    "tieba",
    "tieba.hot-topic",
    "tieba",
    "hot-topic",
    "百度贴吧",
    "百度贴吧热议",
    "https://tieba.baidu.com",
    "adapter",
    600,
    ["general"],
    "blue",
    120,
    10,
    "热议",
  ),
  channel(
    "toutiao",
    "toutiao.hot-board",
    "toutiao",
    "hot-board",
    "今日头条",
    "今日头条热榜",
    "https://www.toutiao.com",
    "adapter",
    600,
    ["general"],
    "red",
    130,
    10,
    "热榜",
  ),
  channel(
    "ithome",
    "ithome.news",
    "ithome",
    "news",
    "IT之家",
    "IT之家最新",
    "https://www.ithome.com",
    "adapter",
    600,
    ["tech"],
    "red",
    140,
    10,
    "最新",
  ),
  channel(
    "thepaper",
    "thepaper.hot-list",
    "thepaper",
    "hot-list",
    "澎湃新闻",
    "澎湃新闻热榜",
    "https://www.thepaper.cn",
    "adapter",
    1800,
    ["general"],
    "gray",
    150,
    10,
    "热榜",
  ),
  channel(
    "sputniknewscn",
    "sputniknewscn.news",
    "sputniknewscn",
    "news",
    "卫星通讯社",
    "卫星通讯社中文网",
    "https://sputniknews.cn",
    "adapter",
    600,
    ["world"],
    "orange",
    160,
    10,
    "新闻",
  ),
  channel(
    "cankaoxiaoxi",
    "cankaoxiaoxi.news",
    "cankaoxiaoxi",
    "news",
    "参考消息",
    "参考消息新闻",
    "https://china.cankaoxiaoxi.com",
    "adapter",
    1800,
    ["world"],
    "red",
    170,
    10,
    "新闻",
  ),
  channel(
    "pcbeta-windows11",
    "pcbeta.windows11",
    "pcbeta",
    "windows11",
    "远景论坛",
    "远景论坛 Win11",
    "https://bbs.pcbeta.com",
    "rss",
    300,
    ["tech"],
    "blue",
    180,
    10,
    "Win11",
    30,
    "https://bbs.pcbeta.com/forum.php?mod=rss&fid=563&auth=0",
  ),
  channel(
    "cls-telegraph",
    "cls.telegraph",
    "cls",
    "telegraph",
    "财联社",
    "财联社电报",
    "https://www.cls.cn",
    "adapter",
    300,
    ["finance"],
    "red",
    190,
    10,
    "电报",
  ),
  channel(
    "cls-depth",
    "cls.depth",
    "cls",
    "depth",
    "财联社",
    "财联社深度",
    "https://www.cls.cn",
    "adapter",
    600,
    ["finance"],
    "red",
    190,
    20,
    "深度",
  ),
  channel(
    "cls-hot",
    "cls.hot",
    "cls",
    "hot",
    "财联社",
    "财联社热门",
    "https://www.cls.cn",
    "adapter",
    600,
    ["finance"],
    "red",
    190,
    30,
    "热门",
  ),
  channel(
    "xueqiu-hotstock",
    "xueqiu.hotstock",
    "xueqiu",
    "hotstock",
    "雪球",
    "雪球热门股票",
    "https://xueqiu.com",
    "adapter",
    120,
    ["finance"],
    "blue",
    200,
    10,
    "热门股票",
  ),
  channel(
    "gelonghui",
    "gelonghui.news",
    "gelonghui",
    "news",
    "格隆汇",
    "格隆汇事件",
    "https://www.gelonghui.com",
    "adapter",
    120,
    ["finance"],
    "blue",
    210,
    10,
    "事件",
  ),
  channel(
    "fastbull-express",
    "fastbull.express",
    "fastbull",
    "express",
    "法布财经",
    "法布财经快讯",
    "https://www.fastbull.cn",
    "adapter",
    120,
    ["finance"],
    "emerald",
    220,
    10,
    "快讯",
  ),
  channel(
    "fastbull-news",
    "fastbull.news",
    "fastbull",
    "news",
    "法布财经",
    "法布财经头条",
    "https://www.fastbull.cn",
    "adapter",
    1800,
    ["finance"],
    "emerald",
    220,
    20,
    "头条",
  ),
  channel(
    "solidot",
    "solidot.news",
    "solidot",
    "news",
    "Solidot",
    "Solidot",
    "https://solidot.org",
    "rss",
    3600,
    ["tech"],
    "teal",
    230,
    10,
    "资讯",
    30,
    "https://www.solidot.org/index.rss",
    true,
    true,
    "active",
  ),
  channel(
    "hackernews",
    "hackernews.top",
    "hackernews",
    "top",
    "Hacker News",
    "Hacker News 热榜",
    "https://news.ycombinator.com/",
    "adapter",
    600,
    ["tech"],
    "orange",
    240,
    10,
    "热榜",
  ),
  channel(
    "producthunt",
    "producthunt.posts",
    "producthunt",
    "posts",
    "Product Hunt",
    "Product Hunt 热榜",
    "https://www.producthunt.com/",
    "rss",
    600,
    ["tech"],
    "red",
    250,
    10,
    "Posts",
    30,
    "https://www.producthunt.com/feed",
  ),
  channel(
    "github-trending-today",
    "github.trending-today",
    "github",
    "trending-today",
    "GitHub",
    "GitHub Trending",
    "https://github.com/",
    "adapter",
    600,
    ["tech"],
    "gray",
    260,
    10,
    "Today",
  ),
  channel(
    "bilibili-hot-search",
    "bilibili.hot-search",
    "bilibili",
    "hot-search",
    "哔哩哔哩",
    "哔哩哔哩热搜",
    "https://www.bilibili.com",
    "adapter",
    600,
    ["general", "entertainment"],
    "blue",
    270,
    10,
    "热搜",
  ),
  channel(
    "bilibili-hot-video",
    "bilibili.hot-video",
    "bilibili",
    "hot-video",
    "哔哩哔哩",
    "哔哩哔哩热门视频",
    "https://www.bilibili.com",
    "adapter",
    600,
    ["general", "entertainment"],
    "blue",
    270,
    20,
    "热门视频",
  ),
  channel(
    "bilibili-ranking",
    "bilibili.ranking",
    "bilibili",
    "ranking",
    "哔哩哔哩",
    "哔哩哔哩排行榜",
    "https://www.bilibili.com",
    "adapter",
    1800,
    ["general", "entertainment"],
    "blue",
    270,
    30,
    "排行榜",
  ),
  channel(
    "kuaishou",
    "kuaishou.hot-list",
    "kuaishou",
    "hot-list",
    "快手",
    "快手热榜",
    "https://www.kuaishou.com",
    "adapter",
    600,
    ["general", "entertainment"],
    "orange",
    280,
    10,
    "热榜",
  ),
  channel(
    "kaopu",
    "kaopu.news",
    "kaopu",
    "news",
    "靠谱新闻",
    "靠谱新闻",
    "https://kaopu.news/",
    "adapter",
    1800,
    ["world"],
    "gray",
    290,
    10,
    "新闻",
  ),
  channel(
    "jin10",
    "jin10.flash",
    "jin10",
    "flash",
    "金十数据",
    "金十数据快讯",
    "https://www.jin10.com",
    "adapter",
    600,
    ["finance"],
    "blue",
    300,
    10,
    "快讯",
  ),
  channel(
    "baidu",
    "baidu.hot-search",
    "baidu",
    "hot-search",
    "百度热搜",
    "百度热搜",
    "https://www.baidu.com",
    "adapter",
    600,
    ["general"],
    "blue",
    310,
    10,
    "热搜",
  ),
  channel(
    "nowcoder",
    "nowcoder.hot-search",
    "nowcoder",
    "hot-search",
    "牛客",
    "牛客热榜",
    "https://www.nowcoder.com",
    "adapter",
    600,
    ["general", "tech"],
    "blue",
    320,
    10,
    "热榜",
  ),
  channel(
    "sspai",
    "sspai.hot",
    "sspai",
    "hot",
    "少数派",
    "少数派热门文章",
    "https://sspai.com",
    "adapter",
    600,
    ["tech"],
    "red",
    330,
    10,
    "热门文章",
  ),
  channel(
    "juejin",
    "juejin.hot",
    "juejin",
    "hot",
    "稀土掘金",
    "稀土掘金热榜",
    "https://juejin.cn",
    "adapter",
    600,
    ["tech"],
    "blue",
    340,
    10,
    "热榜",
  ),
  channel(
    "ifeng",
    "ifeng.hot",
    "ifeng",
    "hot",
    "凤凰网",
    "凤凰网热点资讯",
    "https://www.ifeng.com",
    "adapter",
    600,
    ["general"],
    "red",
    350,
    10,
    "热点资讯",
  ),
  channel(
    "chongbuluo-latest",
    "chongbuluo.latest",
    "chongbuluo",
    "latest",
    "虫部落",
    "虫部落最新",
    "https://www.chongbuluo.com/forum.php?mod=guide&view=newthread",
    "rss",
    1800,
    ["general"],
    "green",
    360,
    10,
    "最新",
    30,
    "https://www.chongbuluo.com/forum.php?mod=rss&view=newthread",
  ),
  channel(
    "chongbuluo-hot",
    "chongbuluo.hot",
    "chongbuluo",
    "hot",
    "虫部落",
    "虫部落最热",
    "https://www.chongbuluo.com/forum.php?mod=guide&view=hot",
    "adapter",
    1800,
    ["general"],
    "green",
    360,
    20,
    "最热",
  ),
  channel(
    "douban",
    "douban.hot-movie",
    "douban",
    "hot-movie",
    "豆瓣",
    "豆瓣热门电影",
    "https://www.douban.com",
    "adapter",
    600,
    ["general", "entertainment"],
    "green",
    370,
    10,
    "热门电影",
  ),
  channel(
    "steam",
    "steam.online",
    "steam",
    "online",
    "Steam",
    "Steam 在线人数",
    "https://store.steampowered.com",
    "adapter",
    600,
    ["world", "entertainment"],
    "blue",
    380,
    10,
    "在线人数",
  ),
  channel(
    "tencent-hot",
    "tencent.hot",
    "tencent",
    "hot",
    "腾讯新闻",
    "腾讯新闻综合早报",
    "https://news.qq.com/tag/aEWqxLtdgmQ=",
    "adapter",
    1800,
    ["general"],
    "blue",
    390,
    10,
    "综合早报",
  ),
  channel(
    "freebuf",
    "freebuf.feed",
    "freebuf",
    "feed",
    "Freebuf",
    "Freebuf 网络安全",
    "https://www.freebuf.com/",
    "rss",
    600,
    ["tech"],
    "green",
    400,
    10,
    "网络安全",
    30,
    "https://www.freebuf.com/feed",
  ),
  channel(
    "qqvideo-tv-hotsearch",
    "qqvideo.tv-hotsearch",
    "qqvideo",
    "tv-hotsearch",
    "腾讯视频",
    "腾讯视频电视剧热搜榜",
    "https://v.qq.com/channel/tv",
    "adapter",
    1800,
    ["general", "entertainment"],
    "blue",
    410,
    10,
    "热搜榜",
  ),
  channel(
    "iqiyi-hot-ranklist",
    "iqiyi.hot-ranklist",
    "iqiyi",
    "hot-ranklist",
    "爱奇艺",
    "爱奇艺热播榜",
    "https://www.iqiyi.com",
    "adapter",
    1800,
    ["general", "entertainment"],
    "green",
    420,
    10,
    "热播榜",
  ),
]

export const newsnowChannelCatalog: NewsnowChannelCatalogEntry[] =
  catalogInputs.map((entry) => ({
    ...entry,
    description: `${entry.siteName} 的 NewsNow 内置数据源。`,
    channelType: inferChannelType(entry),
    displayStyle: inferDisplayStyle(entry),
    itemLimit: entry.itemLimit,
    metaDisplay: "none",
    metaPosition: "inline",
    showUpdatedAt: true,
    snapshotIntervalSeconds: 7200,
    isCrawlEnabled: entry.isCrawlEnabled,
    isHomeVisible: entry.isHomeVisible,
    isSubscribable: true,
    status: entry.status,
  }))

export const legacyNewsnowDefinitionKeys = new Set([
  "github.trending-today",
  "solidot.news",
  "weibo.hot-search",
  "zhihu.hot-list",
])

function channel(
  sourceId: string,
  definitionKey: string,
  siteSlug: string,
  channelSlug: string,
  siteName: string,
  channelName: string,
  homepageUrl: string,
  collectorType: ChannelCollectorType,
  crawlIntervalSeconds: number,
  categorySlugs: string[],
  colorPreset: ChannelColorPreset,
  siteSort: number,
  sort: number,
  subtitle: string | null,
  itemLimit = 30,
  rssUrl?: string,
  isCrawlEnabled = false,
  isHomeVisible = false,
  status: "draft" | "active" | "disabled" = "draft",
): CatalogInput {
  return {
    sourceId,
    definitionKey,
    siteSlug,
    channelSlug,
    siteName,
    channelName,
    homepageUrl,
    collectorType,
    rssUrl,
    crawlIntervalSeconds,
    categorySlugs,
    colorPreset,
    siteSort,
    sort,
    subtitle,
    itemLimit,
    isCrawlEnabled,
    isHomeVisible,
    status,
  }
}

function inferChannelType(entry: CatalogInput): ChannelType {
  if (
    entry.definitionKey.includes("video") ||
    entry.siteSlug === "bilibili" ||
    entry.siteSlug === "iqiyi" ||
    entry.siteSlug === "qqvideo"
  ) {
    return "video"
  }

  if (entry.collectorType === "rss") {
    return "feed"
  }

  if (
    entry.channelSlug.includes("hot") ||
    entry.channelSlug.includes("ranking") ||
    entry.channelSlug.includes("renqi") ||
    entry.channelSlug.includes("online")
  ) {
    return "rank"
  }

  return "news"
}

function inferDisplayStyle(entry: CatalogInput): ChannelDisplayStyle {
  if (inferChannelType(entry) === "rank") {
    return "rank"
  }

  if (inferChannelType(entry) === "video") {
    return "card"
  }

  return "news"
}
